import { Header } from "@/components/Header/Header";
import { ReduxProvider } from "@/components/ReduxProvider/ReduxProvider";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
